# Generated by Django 5.2.1 on 2025-07-02 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='address',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='room',
            name='total_seats',
        ),
        migrations.RemoveField(
            model_name='seattype',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='app_trans_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pay_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='select_seat_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cinema',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='street',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cinema',
            name='ward',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=210, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='no_column',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='no_row',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seattype',
            name='short_name',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_to_select_seat', 'Pending to Select Seat'), ('pending_to_pay', 'Pending to Pay'), ('paid', 'Paid'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='pending_to_select_seat', max_length=32, verbose_name='Trạng thái đặt vé'),
        ),
        migrations.AlterField(
            model_name='bookingseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='app.booking'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_debit', 'Credit/Debit Card'), ('e_wallet', 'E-Wallet'), ('internet_banking', 'Internet Banking')], default='credit_debit', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.cinema'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='app.movie'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='app.room'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='app.actor'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='app.genre'),
        ),
        migrations.CreateModel(
            name='SeatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_prices', to='app.seattype')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_prices', to='app.showtime')),
            ],
            options={
                'unique_together': {('showtime', 'seat_type')},
            },
        ),
    ]
