# Generated by Django 5.2.1 on 2025-05-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seattype_seat_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seattype',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
