# Generated by Django 5.2.1 on 2025-07-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_actor_genre_remove_cinema_address_remove_movie_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seattype',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
