# Generated by Django 5.2.1 on 2025-05-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking_expired_at_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingseat',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('hold', 'Hold'), ('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
