# Generated by Django 5.2.1 on 2025-06-01 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bookingseat_final_price_bookingseat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingseat',
            name='status',
        ),
        migrations.AlterField(
            model_name='bookingseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='app.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_debit', 'Credit/Debit Card'), ('e_wallet', 'E-Wallet'), ('internet_banking', 'Internet Banking')], default='credit_debit', max_length=20),
        ),
    ]
