# Generated by Django 5.2.1 on 2025-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_bookingseat_status_alter_bookingseat_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='app_trans_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
