# Generated by Django 5.2.1 on 2025-07-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_cinema_address_cinema_district_cinema_street_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='room',
            name='no_column',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='no_row',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.cinema'),
        ),
    ]
