# Generated by Django 5.2.1 on 2025-07-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_room_total_seats_room_no_column_room_no_row_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seattype',
            name='extra_price',
        ),
        migrations.AddField(
            model_name='seat',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SeatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seattype')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_prices', to='app.showtime')),
            ],
            options={
                'unique_together': {('showtime', 'seat_type')},
            },
        ),
    ]
